#!/usr/bin/env python3

# show the CPU and MEM usage percentage of each user on all nodes.

import re
import subprocess
from datetime import datetime
from multiprocessing import Pool

def read_status(server):
    user_top = '/path/to/bin/user_top'
    return (server, str(subprocess.check_output(['ssh', server, user_top]), 'utf-8'))

server_names = ['host1', 'host2', 'host3', 'host4']

pool = Pool(8)
results = pool.map(read_status, server_names)
pool.close()
pool.join()

user_top_outputs = {}
for srv, res in results:
    user_top_outputs[srv] = res

print()

for x in server_names:
    lines = user_top_outputs[x].split('\n')
    x = '%-7s' % x
    first_line = x + '  ' + lines[0]
    print('-' * 50)
    print(first_line)
    for idx in range(1, len(lines)):
        print(' ' * len(x) + '  ' + lines[idx])

print()
